---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
# Sign_up
  "/api/v1/auth":
    post:
      summary: Sign Up
      tags:
      - User
      description: Creates a User from provided data
      operationId: createNewUser
      parameters: []
      responses:
        '200':
          description: User created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  email:
                    type: string
                  password:
                    type: string
                  password_confirmation:
                    type: string

# Sign_in
  "/api/v1/auth/sign_in":
    post:
      summary: Sign in
      tags:
      - User
      description: Sign-in a User from provided data. In response you will get access
        to the entire application.
      parameters: []
      responses:
        '200':
          description: User Sign-in
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

  # App Users Spec
  "/api/v1/app_users/{id}":
    get:
      summary: Show User Profile
      tags:
      - Profile
      description: Show user profile by giving its id
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content: {}
        '422':
          description: invalid request
          content: {}

  #  Country Module
  "/api/v1/countries":
    get:
      summary: Show All countries
      tags:
      - Countries
      description: Info Related to All Countries
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      responses:
        '200':
          description: All Countries
          content: {}
        '422':
          description: invalid request
          content: {}
    post:
      summary: Create Country
      tags:
      - Countries
      description: "Creates a New Country"
      operationId: postCountryCreation
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Country Created
          content: {}
        '404':
          description: Country not created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                country:
                  type: object
                  properties:
                    name:
                      type: string
                    comments:
                      type: text

  "/api/v1/countries/{id}":
    get:
      summary: Show country
      tags:
      - Countries
      description: Show a country by giving its id
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content: {}
        '422':
          description: invalid request
          content: {}
    put:
      summary: Update a country
      tags:
      - Countries
      description: Update a country by giving its id
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                country:
                  type: object
                  properties:
                    name:
                      type: string
                    comments:
                      type: text
    delete:
      summary: Delete country
      tags:
      - Countries
      description: Delete a country by giving its id
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content: {}
        '422':
          description: invalid request
          content: {}
          "/api/v1/countries/{id}":

  #  City Module
  "/api/v1/cities":
    get:
      summary: Show All cities
      tags:
      - Cities
      description: Info Related to All Cities
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      responses:
        '200':
          description: All Cities
          content: {}
        '422':
          description: invalid request
          content: {}
    post:
      summary: Create City
      tags:
      - Cities
      description: "Creates a New City"
      operationId: postCityCreation
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      responses:
        '200':
          description: City Created
          content: {}
        '404':
          description: City not created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: object
                  properties:
                    name:
                      type: string
                    comments:
                      type: text

  "/api/v1/cities/{id}":
    get:
      summary: Show city
      tags:
      - Cities
      description: Show a city by giving its id
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content: {}
        '422':
          description: invalid request
          content: {}
    put:
      summary: Update a city
      tags:
      - Cities
      description: Update a city by giving its id
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: object
                  properties:
                    name:
                      type: string
                    comments:
                      type: text
    delete:
      summary: Delete city
      tags:
      - Cities
      description: Delete a city by giving its id
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content: {}
        '422':
          description: invalid request
          content: {}
          "/api/v1/cities/{id}":
servers:
- url: https://portal.tractoronline.com.pk/
- url: http://localhost:4000
