---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth":
    post:
      summary: Sign Up
      tags:
      - user
      description: Creates a User from provided data
      operationId: createNewUser
      parameters: []
      responses:
        '200':
          description: User created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  email:
                    type: string
                  password:
                    type: string
                  password_confirmation:
                    type: string
  "/api/v1/auth/sign_in":
    post:
      summary: Sign in
      tags:
      - user
      description: Sign-in a User from provided data. In response you will get access
        to the entire application.
      parameters: []
      responses:
        '200':
          description: User Sign-in
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:4000
